/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRLEN_H_RPCGEN
#define _STRLEN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct strobject {
	char text[100];
};
typedef struct strobject strobject;

#define STRLENGHT 1
#define STRLENGHT_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define COUNT 1
extern  int * count_1(strobject *, CLIENT *);
extern  int * count_1_svc(strobject *, struct svc_req *);
extern int strlenght_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COUNT 1
extern  int * count_1();
extern  int * count_1_svc();
extern int strlenght_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_strobject (XDR *, strobject*);

#else /* K&R C */
extern bool_t xdr_strobject ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRLEN_H_RPCGEN */
