/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "strlen.h"


void
strlenght_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	strobject  count_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, STRLENGHT, STRLENGHT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char msg[100];
	printf("Insira o texto para contar o tamanho: \n");
	scanf("%s", msg);
	
	count_1_arg.text[0] = '\0';
	strcat(count_1_arg.text, msg);
	result_1 = count_1(&count_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Numero de caracteres: %i\n", *result_1);	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	strlenght_1 (host);
exit (0);
}
