/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "strlen.h"

int *
count_1_svc(strobject *argp, struct svc_req *rqstp)
{
	static int  result;

	int lenght = strlen(argp->text);
	result = lenght;
	return &result;
}
