/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"

message *
send_1_svc(message *argp, struct svc_req *rqstp)
{
	static message  result;

	printf("Recebido: %s", argp->message);
	result.message[0] = '\0';
	strcat(result.message, argp->message);

	return &result;
}
