/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"


void
message_1(char *host)
{
	CLIENT *clnt;
	message  *result_1;
	message  send_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGE, MESSAGE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	char msg[100];
	printf("Insira a mensagem: \n");
	scanf("%s", msg);
	
	send_1_arg.message[0] = '\0';
	strcat(send_1_arg.message, msg);
	result_1 = send_1(&send_1_arg, clnt);
	if (result_1 == (message *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Recebido: %s\n", result_1->message);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	message_1 (host);
exit (0);
}
