/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONACCI_H_RPCGEN
#define _FIBONACCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct FIB {
	int number;
};
typedef struct FIB FIB;

#define FIBO 1
#define FIBO_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCFIBO 1
extern  int * calcfibo_1(FIB *, CLIENT *);
extern  int * calcfibo_1_svc(FIB *, struct svc_req *);
extern int fibo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCFIBO 1
extern  int * calcfibo_1();
extern  int * calcfibo_1_svc();
extern int fibo_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FIB (XDR *, FIB*);

#else /* K&R C */
extern bool_t xdr_FIB ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONACCI_H_RPCGEN */
