/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibonacci.h"

int fib(int n)                             
    {                                          
     int i, fib1 = 1, fib2 = 1, soma;         
      for (i = 3; i <= n; i = i + 1)           
      {                                        
        soma = fib1 + fib2;                    
        fib1 = fib2;                           
       	fib2 = soma;                           
     }                                        
     return fib2;                             
} 


int *
calcfibo_1_svc(FIB *argp, struct svc_req *rqstp)
{
	static int  result;

	int number = argp->number;
	printf("Recebido: %i\n", number);
	int fib_result = fib(number);

	printf("Resultado: %i\n", fib_result);
	result = fib_result;
	return &result;
}

