/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibonacci.h"

void
fibo_1(char *host, char *host2, char *host3)
{
	printf("Conectando...\n");
	int error = 0;
	int count = 0;
	CLIENT *clnt;
	int  *result_1;
	FIB  calcfibo_1_arg;

	do{
		printf("Tentativa de conexao %i\n", count+1);
		switch(count){
			case 0:	
				clnt = clnt_create (host, FIBO, FIBO_1, "udp");
				break;
			case 1:
				clnt = clnt_create (host2, FIBO, FIBO_1, "udp");
				break;
			case 2: 
				clnt = clnt_create (host3, FIBO, FIBO_1, "udp");
				break;	
		}
		if (clnt == NULL) {
			printf("Erro de conexao\n");
			//clnt_perror (clnt, "call failed");
			error = 1;
		}else{
			error = 0;		
		}
		count++;
	}while(error != 0);


	printf("Insira um numero: \n");
	scanf("%i", &calcfibo_1_arg.number);

	result_1 = calcfibo_1(&calcfibo_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		error = 1;
	}else{
		printf("Resultado do calculo de fibonacci: %i\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host1;
	char *host2;
	char *host3;
	
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host1 = argv[1];
	host2 = argv[2];
	host3 = argv[3];

	printf ("Hosts recebidos:\n%s\n%s\n%s\n", host1, host2, host3);
	fibo_1 (host1, host2, host3);
	exit (0);
}
