/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Recebido solicitacao do usuario\n");

	printf("Valor de n1: %i\n", argp->n1);
	printf("Valor de n2: %i\n", argp->n2);

	result = argp->n1 + argp-> n2;

	printf("Valor da soma: %i\n", result);
	
	return &result;
}
