/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "greater_lower.h"

response *
calculate_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static response  result;

	int n1 = argp->n1;
	int n2 = argp->n2;
	int n3 = argp->n3;

	int greater;
	int lower;

	if(n1>=n2 && n1>=n3){
		greater = n1;	
	}else if(n2>=n1 && n2>=n3){
		greater = n2;	
	}else{
		greater = n3;	
	}

	if(n1<=n2 && n1<=n3){
		lower = n1;	
	}else if(n2<=n1 && n2<=n3){
		lower = n2;	
	}else{
		lower = n3;	
	}

	result.lower = lower;
	result.greater = greater;

	return &result;
}
