/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "greater_lower.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->greater))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lower))
		 return FALSE;
	return TRUE;
}
