/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "greater_lower.h"


void
greater_1(char *host)
{
	CLIENT *clnt;
	response  *result_1;
	numbers  calculate_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GREATER, GREATER_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int n1;
	int n2;
	int n3;
	printf("Digite 3 numeros inteiros: \n");
	scanf("%i %i %i", &n1, &n2, &n3);
	
	calculate_1_arg.n1 = n1;
	calculate_1_arg.n2 = n2;
	calculate_1_arg.n3 = n3;
	result_1 = calculate_1(&calculate_1_arg, clnt);
	if (result_1 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("O maior numero e %i\nO menor numero e %i\n", result_1->greater, result_1->lower);	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	greater_1 (host);
exit (0);
}
